name: Status check functions
on: workflow_dispatch
jobs:
    test-check-functions:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "Is this work failure?"
              if: ${{failure()}}
            - run: echo "Is this work success?"
              if: ${{success()}}