name: Condtions workflow
on: workflow_dispatch
jobs:
    check-conditions-workflow:
        if: ${{github.actor == 'pxxguin'}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "Welcome, ${{github.actor}}"