name: Naming
on: workflow_dispatch
jobs:
    naming-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Echo current github actor
              run: echo "${{github.actor}}"
            - name: Echo current repository
              run: echo "${{github.action_repository}}"