name: Python test 2
on:
    push:
        paths: ['src/**/*.py']
        branches: ['main']
jobs:
    test-python:
        runs-on: ubuntu-latest
        steps:
            - name: Excute actions/checktout@v7
              uses: actions/checkout@v7
            - name: Excute actions/setup-python@v6
              uses: actions/setup-python@v6
              with:
                python-version: '3.11.15'
                cache: pip
            - name: Excute pip install
              run: pip install -r requirements.txt --no-cache-dir
            - name: Execute pytest
              run: pytest src/tests
