name: This is markdown test
on: push
jobs:
    logs:
        runs-on: ubuntu-latest
        steps:
            - run: echo "## :rocket:Patched by ${{github.actor}}" >> "${GITHUB_STEP_SUMMARY}"
            - run: echo "- first main.py is modified by ${{github.actor}}" >> "${GITHUB_STEP_SUMMARY}"
            - run: echo "- At last, we have to where we are." >> "${GITHUB_STEP_SUMMARY}"