name: Matrix
on: push
jobs:
    print:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, maxos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - run: echo "${RUNNER_OS}"
              shell: bash