name: What is the impact using actions
on: workflow_dispatch
jobs:
    with-using-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Get my code
              uses: actions/checkout@v7
            
            - name: Read current files
              run: ls -ali